# Generated by Django 2.0.5 on 2018-05-11 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient_hdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_hdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('S', 'Snack'), ('D', 'Drink')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item_ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Ingredient_hdr')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item_hdr')),
            ],
        ),
        migrations.CreateModel(
            name='Related_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_hdr', to='menu.Item_hdr')),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='menu.Item_hdr')),
            ],
        ),
    ]
