# Generated by Django 2.0.5 on 2018-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_ingredients',
            name='ingredient',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Ingredient_hdr',
        ),
    ]
